<a href="https://colab.research.google.com/github/mollah2022/-Bus-Ticket-Booking-App/blob/main/employees_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/employees_system_dataset.csv")

In [3]:
df.head()

,employee_id,full_name,age,department,job_title,salary,city,joining_date,performance_score,is_active
0,1,Employee 1,45,Finance,Analyst,32500,Chattogram,2021-04-01,2,True
1,2,Employee 2,23,IT,Software Engineer,97500,Chattogram,2020-12-22,2,True
2,3,Employee 3,35,HR,Executive,115000,Sylhet,2022-03-25,3,True
3,4,Employee 4,32,Finance,Analyst,97500,Chattogram,2021-10-15,3,True
4,5,Employee 5,25,Finance,Manager,90000,Sylhet,2021-01-14,3,True

In [4]:
df.tail()

,employee_id,full_name,age,department,job_title,salary,city,joining_date,performance_score,is_active
45,46,Employee 46,41,HR,Accountant,75000,Khulna,2023-01-20,2,True
46,47,Employee 47,30,IT,Software Engineer,107500,Rajshahi,2025-09-01,3,True
47,48,Employee 48,46,HR,Accountant,82500,Khulna,2020-01-15,2,False
48,49,Employee 49,22,IT,Software Engineer,117500,Chattogram,2024-10-17,5,True
49,50,Employee 50,26,Sales,Analyst,117500,Dhaka,2024-02-21,3,True

In [5]:
new_df = df.dropna()

print(new_df.to_string())

    employee_id    full_name  age department          job_title  salary        city joining_date  performance_score  is_active
0             1   Employee 1   45    Finance            Analyst   32500  Chattogram   2021-04-01                  2       True
1             2   Employee 2   23         IT  Software Engineer   97500  Chattogram   2020-12-22                  2       True
2             3   Employee 3   35         HR          Executive  115000      Sylhet   2022-03-25                  3       True
3             4   Employee 4   32    Finance            Analyst   97500  Chattogram   2021-10-15                  3       True
4             5   Employee 5   25    Finance            Manager   90000      Sylhet   2021-01-14                  3       True
5             6   Employee 6   25      Sales  Software Engineer  115000      Sylhet   2025-02-24                  3       True
6             7   Employee 7   23    Support            Analyst   40000      Khulna   2022-02-26                  1       True
7             8   Employee 8   30      Sales         Accountant   90000      Khulna   2021-02-17                  2       True
8             9   Employee 9   43    Finance         Accountant   62500       Dhaka   2023-12-26                  5       True
9            10  Employee 10   27      Sales          Executive   67500      Khulna   2025-12-27                  5       True
10           11  Employee 11   29         IT            Manager   37500    Rajshahi   2023-08-21                  3       True
11           12  Employee 12   50    Support            Manager  120000  Chattogram   2022-05-14                  4      False
12           13  Employee 13   30         HR            Analyst   52500      Sylhet   2025-02-22                  5       True
13           14  Employee 14   33         HR            Analyst   92500      Sylhet   2024-10-20                  4       True
14           15  Employee 15   26    Support            Analyst   47500    Rajshahi   2020-07-11                  5       True
15           16  Employee 16   41      Sales         HR Officer   90000      Khulna   2024-04-25                  5       True
16           17  Employee 17   46    Finance         Accountant  115000      Khulna   2021-04-14                  1       True
17           18  Employee 18   36         IT         Accountant   55000      Khulna   2024-11-15                  5       True
18           19  Employee 19   49    Support            Manager   45000      Sylhet   2025-09-10                  5       True
19           20  Employee 20   46         HR         HR Officer   87500      Sylhet   2021-09-18                  1       True
20           21  Employee 21   25    Finance            Manager   32500  Chattogram   2025-06-24                  1       True
21           22  Employee 22   45      Sales  Software Engineer   42500      Sylhet   2020-11-18                  2       True
22           23  Employee 23   27    Finance         HR Officer  117500      Sylhet   2025-04-30                  4       True
23           24  Employee 24   34    Support         Accountant   77500      Khulna   2022-04-03                  4      False
24           25  Employee 25   29         IT            Manager   67500       Dhaka   2021-05-10                  5       True
25           26  Employee 26   24    Support         Accountant   30000       Dhaka   2022-06-21                  2       True
26           27  Employee 27   24  Marketing            Analyst   82500      Khulna   2020-05-08                  4       True
27           28  Employee 28   40      Sales            Analyst  120000    Rajshahi   2021-06-25                  4       True
28           29  Employee 29   43      Sales            Manager   45000    Rajshahi   2021-01-21                  4      False
29           30  Employee 30   23      Sales         Accountant   45000      Khulna   2020-08-09                  1       True
30           31  Employee 31   39      Sales            Analyst   60000    Rajshahi   2022-02-23                  2       True
31           32  Employee 32   49         IT          Executive   67500      Sylhet   2025-03-09                  1       True
32           33  Employee 33   46         HR            Analyst   42500    Rajshahi   2020-03-01                  4      False
33           34  Employee 34   50         IT            Analyst   92500    Rajshahi   2022-05-25                  1      False
34           35  Employee 35   31      Sales         Accountant  102500      Sylhet   2022-12-22                  4       True
35           36  Employee 36   28         IT         HR Officer   75000      Sylhet   2022-02-16                  1       True
36           37  Employee 37   40      Sales         HR Officer   37500      Sylhet   2020-08-22                  2       True
37           38  Employee 38   49         HR  Software Engineer   42500      Sylhet   2025-09-11                  1       True
38           39  Employee 39   50  Marketing            Analyst   47500      Sylhet   2024-07-11                  5       True
39           40  Employee 40   43  Marketing         HR Officer   95000      Sylhet   2020-12-01                  3       True
40           41  Employee 41   29    Finance          Executive   80000  Chattogram   2022-04-16                  3      False
41           42  Employee 42   22      Sales         HR Officer   40000      Sylhet   2023-07-19                  1       True
42           43  Employee 43   30         HR            Manager  110000       Dhaka   2022-05-23                  2       True
43           44  Employee 44   36  Marketing         Accountant   55000      Khulna   2023-03-13                  5       True
44           45  Employee 45   50         HR            Manager   45000       Dhaka   2023-05-11                  1       True
45           46  Employee 46   41         HR         Accountant   75000      Khulna   2023-01-20                  2       True
46           47  Employee 47   30         IT  Software Engineer  107500    Rajshahi   2025-09-01                  3       True
47           48  Employee 48   46         HR         Accountant   82500      Khulna   2020-01-15                  2      False
48           49  Employee 49   22         IT  Software Engineer  117500  Chattogram   2024-10-17                  5       True
49           50  Employee 50   26      Sales            Analyst  117500       Dhaka   2024-02-21                  3       True

In [7]:
df.dropna(inplace = True)

print(df.to_string())

    employee_id    full_name  age department          job_title  salary        city joining_date  performance_score  is_active
0             1   Employee 1   45    Finance            Analyst   32500  Chattogram   2021-04-01                  2       True
1             2   Employee 2   23         IT  Software Engineer   97500  Chattogram   2020-12-22                  2       True
2             3   Employee 3   35         HR          Executive  115000      Sylhet   2022-03-25                  3       True
3             4   Employee 4   32    Finance            Analyst   97500  Chattogram   2021-10-15                  3       True
4             5   Employee 5   25    Finance            Manager   90000      Sylhet   2021-01-14                  3       True
5             6   Employee 6   25      Sales  Software Engineer  115000      Sylhet   2025-02-24                  3       True
6             7   Employee 7   23    Support            Analyst   40000      Khulna   2022-02-26                  1       True
7             8   Employee 8   30      Sales         Accountant   90000      Khulna   2021-02-17                  2       True
8             9   Employee 9   43    Finance         Accountant   62500       Dhaka   2023-12-26                  5       True
9            10  Employee 10   27      Sales          Executive   67500      Khulna   2025-12-27                  5       True
10           11  Employee 11   29         IT            Manager   37500    Rajshahi   2023-08-21                  3       True
11           12  Employee 12   50    Support            Manager  120000  Chattogram   2022-05-14                  4      False
12           13  Employee 13   30         HR            Analyst   52500      Sylhet   2025-02-22                  5       True
13           14  Employee 14   33         HR            Analyst   92500      Sylhet   2024-10-20                  4       True
14           15  Employee 15   26    Support            Analyst   47500    Rajshahi   2020-07-11                  5       True
15           16  Employee 16   41      Sales         HR Officer   90000      Khulna   2024-04-25                  5       True
16           17  Employee 17   46    Finance         Accountant  115000      Khulna   2021-04-14                  1       True
17           18  Employee 18   36         IT         Accountant   55000      Khulna   2024-11-15                  5       True
18           19  Employee 19   49    Support            Manager   45000      Sylhet   2025-09-10                  5       True
19           20  Employee 20   46         HR         HR Officer   87500      Sylhet   2021-09-18                  1       True
20           21  Employee 21   25    Finance            Manager   32500  Chattogram   2025-06-24                  1       True
21           22  Employee 22   45      Sales  Software Engineer   42500      Sylhet   2020-11-18                  2       True
22           23  Employee 23   27    Finance         HR Officer  117500      Sylhet   2025-04-30                  4       True
23           24  Employee 24   34    Support         Accountant   77500      Khulna   2022-04-03                  4      False
24           25  Employee 25   29         IT            Manager   67500       Dhaka   2021-05-10                  5       True
25           26  Employee 26   24    Support         Accountant   30000       Dhaka   2022-06-21                  2       True
26           27  Employee 27   24  Marketing            Analyst   82500      Khulna   2020-05-08                  4       True
27           28  Employee 28   40      Sales            Analyst  120000    Rajshahi   2021-06-25                  4       True
28           29  Employee 29   43      Sales            Manager   45000    Rajshahi   2021-01-21                  4      False
29           30  Employee 30   23      Sales         Accountant   45000      Khulna   2020-08-09                  1       True
30           31  Employee 31   39      Sales            Analyst   60000    Rajshahi   2022-02-23                  2       True
31           32  Employee 32   49         IT          Executive   67500      Sylhet   2025-03-09                  1       True
32           33  Employee 33   46         HR            Analyst   42500    Rajshahi   2020-03-01                  4      False
33           34  Employee 34   50         IT            Analyst   92500    Rajshahi   2022-05-25                  1      False
34           35  Employee 35   31      Sales         Accountant  102500      Sylhet   2022-12-22                  4       True
35           36  Employee 36   28         IT         HR Officer   75000      Sylhet   2022-02-16                  1       True
36           37  Employee 37   40      Sales         HR Officer   37500      Sylhet   2020-08-22                  2       True
37           38  Employee 38   49         HR  Software Engineer   42500      Sylhet   2025-09-11                  1       True
38           39  Employee 39   50  Marketing            Analyst   47500      Sylhet   2024-07-11                  5       True
39           40  Employee 40   43  Marketing         HR Officer   95000      Sylhet   2020-12-01                  3       True
40           41  Employee 41   29    Finance          Executive   80000  Chattogram   2022-04-16                  3      False
41           42  Employee 42   22      Sales         HR Officer   40000      Sylhet   2023-07-19                  1       True
42           43  Employee 43   30         HR            Manager  110000       Dhaka   2022-05-23                  2       True
43           44  Employee 44   36  Marketing         Accountant   55000      Khulna   2023-03-13                  5       True
44           45  Employee 45   50         HR            Manager   45000       Dhaka   2023-05-11                  1       True
45           46  Employee 46   41         HR         Accountant   75000      Khulna   2023-01-20                  2       True
46           47  Employee 47   30         IT  Software Engineer  107500    Rajshahi   2025-09-01                  3       True
47           48  Employee 48   46         HR         Accountant   82500      Khulna   2020-01-15                  2      False
48           49  Employee 49   22         IT  Software Engineer  117500  Chattogram   2024-10-17                  5       True
49           50  Employee 50   26      Sales            Analyst  117500       Dhaka   2024-02-21                  3       True

In [8]:
df.fillna(130, inplace = True)

In [9]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [10]:
df.drop_duplicates(inplace = True)

In [11]:
# ============================================================
# Create salary rank within each department
# Highest salary gets Rank = 1
# ============================================================

df["salary_rank"] = (
    df
    .groupby("department")["salary"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [12]:
df["salary_rank"]

0      7.0
1      3.0
2      1.0
3      3.0
4      4.0
5      3.0
6      5.0
7      5.0
8      6.0
9      6.0
10     8.0
11     1.0
12     7.0
13     3.0
14     3.0
15     5.0
16     2.0
17     7.0
18     4.0
19     4.0
20     7.0
21     9.0
22     1.0
23     2.0
24     6.0
25     6.0
26     2.0
27     1.0
28     8.0
29     8.0
30     7.0
31     6.0
32     9.0
33     4.0
34     4.0
35     5.0
36    11.0
37     9.0
38     4.0
39     1.0
40     5.0
41    10.0
42     2.0
43     3.0
44     8.0
45     6.0
46     2.0
47     5.0
48     1.0
49     2.0
Name: salary_rank, dtype: float64

In [13]:
# ============================================================
# Sort by department and salary rank
# ============================================================

result = df.sort_values(
    by=["department", "salary_rank"]
)

In [15]:
print(result)

    employee_id    full_name  age department          job_title  salary  \
22           23  Employee 23   27    Finance         HR Officer  117500
16           17  Employee 17   46    Finance         Accountant  115000
3             4   Employee 4   32    Finance            Analyst   97500
4             5   Employee 5   25    Finance            Manager   90000
40           41  Employee 41   29    Finance          Executive   80000
8             9   Employee 9   43    Finance         Accountant   62500
0             1   Employee 1   45    Finance            Analyst   32500
20           21  Employee 21   25    Finance            Manager   32500
2             3   Employee 3   35         HR          Executive  115000
42           43  Employee 43   30         HR            Manager  110000
13           14  Employee 14   33         HR            Analyst   92500
19           20  Employee 20   46         HR         HR Officer   87500
47           48  Employee 48   46         HR         Accountant   82500
45           46  Employee 46   41         HR         Accountant   75000
12           13  Employee 13   30         HR            Analyst   52500
44           45  Employee 45   50         HR            Manager   45000
32           33  Employee 33   46         HR            Analyst   42500
37           38  Employee 38   49         HR  Software Engineer   42500
48           49  Employee 49   22         IT  Software Engineer  117500
46           47  Employee 47   30         IT  Software Engineer  107500
1             2   Employee 2   23         IT  Software Engineer   97500
33           34  Employee 34   50         IT            Analyst   92500
35           36  Employee 36   28         IT         HR Officer   75000
24           25  Employee 25   29         IT            Manager   67500
31           32  Employee 32   49         IT          Executive   67500
17           18  Employee 18   36         IT         Accountant   55000
10           11  Employee 11   29         IT            Manager   37500
39           40  Employee 40   43  Marketing         HR Officer   95000
26           27  Employee 27   24  Marketing            Analyst   82500
43           44  Employee 44   36  Marketing         Accountant   55000
38           39  Employee 39   50  Marketing            Analyst   47500
27           28  Employee 28   40      Sales            Analyst  120000
49           50  Employee 50   26      Sales            Analyst  117500
5             6   Employee 6   25      Sales  Software Engineer  115000
34           35  Employee 35   31      Sales         Accountant  102500
7             8   Employee 8   30      Sales         Accountant   90000
15           16  Employee 16   41      Sales         HR Officer   90000
9            10  Employee 10   27      Sales          Executive   67500
30           31  Employee 31   39      Sales            Analyst   60000
28           29  Employee 29   43      Sales            Manager   45000
29           30  Employee 30   23      Sales         Accountant   45000
21           22  Employee 22   45      Sales  Software Engineer   42500
41           42  Employee 42   22      Sales         HR Officer   40000
36           37  Employee 37   40      Sales         HR Officer   37500
11           12  Employee 12   50    Support            Manager  120000
23           24  Employee 24   34    Support         Accountant   77500
14           15  Employee 15   26    Support            Analyst   47500
18           19  Employee 19   49    Support            Manager   45000
6             7   Employee 7   23    Support            Analyst   40000
25           26  Employee 26   24    Support         Accountant   30000

          city joining_date  performance_score  is_active  salary_rank
22      Sylhet   2025-04-30                  4       True          1.0
16      Khulna   2021-04-14                  1       True          2.0
3   Chattogram   2021-10-15                  3       True          3.0
4       Sylhet   2021-01-14                  3       True          4.0
40  Chattogram   2022-04-16                  3      False          5.0
8        Dhaka   2023-12-26                  5       True          6.0
0   Chattogram   2021-04-01                  2       True          7.0
20  Chattogram   2025-06-24                  1       True          7.0
2       Sylhet   2022-03-25                  3       True          1.0
42       Dhaka   2022-05-23                  2       True          2.0
13      Sylhet   2024-10-20                  4       True          3.0
19      Sylhet   2021-09-18                  1       True          4.0
47      Khulna   2020-01-15                  2      False          5.0
45      Khulna   2023-01-20                  2       True          6.0
12      Sylhet   2025-02-22                  5       True          7.0
44       Dhaka   2023-05-11                  1       True          8.0
32    Rajshahi   2020-03-01                  4      False          9.0
37      Sylhet   2025-09-11                  1       True          9.0
48  Chattogram   2024-10-17                  5       True          1.0
46    Rajshahi   2025-09-01                  3       True          2.0
1   Chattogram   2020-12-22                  2       True          3.0
33    Rajshahi   2022-05-25                  1      False          4.0
35      Sylhet   2022-02-16                  1       True          5.0
24       Dhaka   2021-05-10                  5       True          6.0
31      Sylhet   2025-03-09                  1       True          6.0
17      Khulna   2024-11-15                  5       True          7.0
10    Rajshahi   2023-08-21                  3       True          8.0
39      Sylhet   2020-12-01                  3       True          1.0
26      Khulna   2020-05-08                  4       True          2.0
43      Khulna   2023-03-13                  5       True          3.0
38      Sylhet   2024-07-11                  5       True          4.0
27    Rajshahi   2021-06-25                  4       True          1.0
49       Dhaka   2024-02-21                  3       True          2.0
5       Sylhet   2025-02-24                  3       True          3.0
34      Sylhet   2022-12-22                  4       True          4.0
7       Khulna   2021-02-17                  2       True          5.0
15      Khulna   2024-04-25                  5       True          5.0
9       Khulna   2025-12-27                  5       True          6.0
30    Rajshahi   2022-02-23                  2       True          7.0
28    Rajshahi   2021-01-21                  4      False          8.0
29      Khulna   2020-08-09                  1       True          8.0
21      Sylhet   2020-11-18                  2       True          9.0
41      Sylhet   2023-07-19                  1       True         10.0
36      Sylhet   2020-08-22                  2       True         11.0
11  Chattogram   2022-05-14                  4      False          1.0
23      Khulna   2022-04-03                  4      False          2.0
14    Rajshahi   2020-07-11                  5       True          3.0
18      Sylhet   2025-09-10                  5       True          4.0
6       Khulna   2022-02-26                  1       True          5.0
25       Dhaka   2022-06-21                  2       True          6.0

# Find the top 3 highest paid employees from every department.

In [16]:
# Sort salary from highest to lowest
sorted_df = df.sort_values(
    by="salary",
    ascending=False
)

In [17]:
# Take top 3 employees from each department
top3 = (
    sorted_df
    .groupby("department")
    .head(3)
    .reset_index(drop=True)
)

In [18]:
# Display required columns
print(
    top3[
        [
            "department",
            "full_name",
            "salary"
        ]
    ]
)

   department    full_name  salary
0     Support  Employee 12  120000
1       Sales  Employee 28  120000
2       Sales  Employee 50  117500
3          IT  Employee 49  117500
4     Finance  Employee 23  117500
5          HR   Employee 3  115000
6     Finance  Employee 17  115000
7       Sales   Employee 6  115000
8          HR  Employee 43  110000
9          IT  Employee 47  107500
10    Finance   Employee 4   97500
11         IT   Employee 2   97500
12  Marketing  Employee 40   95000
13         HR  Employee 14   92500
14  Marketing  Employee 27   82500
15    Support  Employee 24   77500
16  Marketing  Employee 44   55000
17    Support  Employee 15   47500