<a href="https://colab.research.google.com/github/mollah2022/-Bus-Ticket-Booking-App/blob/main/json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_json("/content/drive/MyDrive/employees.json")

In [3]:
df.head()

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [4]:
df.tail()

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [5]:
df.shape

(5, 9)

In [7]:
# Show All Column Names
df.columns

Index(['employee_id', 'name', 'department', 'salary', 'age', 'joining_date',
       'skills', 'address', 'projects'],
      dtype='object')

In [8]:
# Show Data Types

df.dtypes

employee_id      int64
name            object
department      object
salary           int64
age              int64
joining_date    object
skills          object
address         object
projects        object
dtype: object

In [9]:
# Show Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   employee_id   5 non-null      int64
 1   name          5 non-null      object
 2   department    5 non-null      object
 3   salary        5 non-null      int64
 4   age           5 non-null      int64
 5   joining_date  5 non-null      object
 6   skills        5 non-null      object
 7   address       5 non-null      object
 8   projects      5 non-null      object
dtypes: int64(3), object(6)
memory usage: 492.0+ bytes

In [10]:
# Select a single column

df["name"]

0    Sajib Ahmed
1          Rahim
2          Karim
3         Nusrat
4         Tanvir
Name: name, dtype: object

In [12]:
# Select multiple columns

df[["name", "salary"]]

          name  salary
0  Sajib Ahmed   65000
1        Rahim   70000
2        Karim   90000
3       Nusrat   62000
4       Tanvir   95000

In [13]:
type(df[["name", "salary"]])

pandas.core.frame.DataFrame

In [15]:
# Select first row
df.iloc[0]

employee_id                                                   101
name                                                  Sajib Ahmed
department                                       Data Engineering
salary                                                      65000
age                                                            25
joining_date                                           2023-01-15
skills                                      [Python, SQL, Pandas]
address                {'city': 'Dhaka', 'country': 'Bangladesh'}
projects        [{'project_name': 'Sales Dashboard', 'hours': ...
Name: 0, dtype: object

In [16]:
# Select first three rows
df.iloc[0:3]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."

In [17]:
# First three rows and first four columns
df.iloc[0:3, 0:4]

   employee_id         name        department  salary
0          101  Sajib Ahmed  Data Engineering   65000
1          102        Rahim  Data Engineering   70000
2          103        Karim                AI   90000

In [18]:
# Select row with index label 2

df.loc[2]

employee_id                                                   103
name                                                        Karim
department                                                     AI
salary                                                      90000
age                                                            30
joining_date                                           2021-06-01
skills                              [Python, TensorFlow, PyTorch]
address             {'city': 'Rajshahi', 'country': 'Bangladesh'}
projects        [{'project_name': 'Image Classification', 'hou...
Name: 2, dtype: object

In [19]:
# Select name and salary columns
df.loc[:, ["name", "salary"]]

          name  salary
0  Sajib Ahmed   65000
1        Rahim   70000
2        Karim   90000
3       Nusrat   62000
4       Tanvir   95000

In [20]:
# Filter employees whose salary is greater than 70000
df[df["salary"] > 70000]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [21]:
# Filter employees from AI department
df[df["department"] == "AI"]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [22]:
# Exclude AI department
df[df["department"] != "AI"]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."

In [24]:
# Salary greater than or equal to 70000

df[df["salary"] >= 70000]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [25]:
# Salary less than 70000
df[df["salary"] < 70000]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."

In [26]:
# AI employees whose salary is greater than 90000

df[
    (df["department"] == "AI")
    &
    (df["salary"] > 90000)
]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [27]:
# Employees from AI or BI department

df[
    (df["department"] == "AI")
    |
    (df["department"] == "BI")
]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [29]:
# Filter employees from selected departments

df[
    df["department"].isin(
        ["AI", "BI"]
    )
]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [30]:
# Employees whose salary is between 65000 and 90000
df[
    df["salary"].between(
        65000,
        90000
    )
]

,employee_id,name,department,salary,age,joining_date,skills,address,projects
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."

In [31]:
# Sort employees by salary (Lowest -> Highest)

result = df.sort_values(by="salary")

result

,employee_id,name,department,salary,age,joining_date,skills,address,projects
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [32]:
# Sort employees by salary (Highest -> Lowest)

result = df.sort_values(
    by="salary",
    ascending=False
)

result

,employee_id,name,department,salary,age,joining_date,skills,address,projects
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."

In [33]:
# Sort by department first, then salary

result = df.sort_values(
    by=["department", "salary"]
)

result

,employee_id,name,department,salary,age,joining_date,skills,address,projects
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"

In [34]:
# Get employee with highest salary

df.nlargest(
    1,
    "salary"
)

,employee_id,name,department,salary,age,joining_date,skills,address,projects
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."

In [35]:
df.nlargest(
    3,
    "salary"
)

,employee_id,name,department,salary,age,joining_date,skills,address,projects
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho..."
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou..."
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]"

In [36]:
# Get employee with lowest salary

df.nsmallest(
    1,
    "salary"
)

,employee_id,name,department,salary,age,joining_date,skills,address,projects
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour..."

In [37]:
# Show unique department names

df["department"].unique()

array(['Data Engineering', 'AI', 'BI'], dtype=object)

In [38]:
# Count unique departments

df["department"].nunique()

3

In [39]:
# Count employees in each department

df["department"].value_counts()

department
Data Engineering    2
AI                  2
BI                  1
Name: count, dtype: int64

In [40]:
# Show percentage of employees by department
df["department"].value_counts(
    normalize=True
)

department
Data Engineering    0.4
AI                  0.4
BI                  0.2
Name: proportion, dtype: float64

In [41]:
# Create salary rank column

df["salary_rank"] = df["salary"].rank(
    ascending=False
)

df

,employee_id,name,department,salary,age,joining_date,skills,address,projects,salary_rank
0,101,Sajib Ahmed,Data Engineering,65000,25,2023-01-15,"[Python, SQL, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Sales Dashboard', 'hours': ...",4.0
1,102,Rahim,Data Engineering,70000,29,2022-08-10,"[Python, Spark, Airflow]","{'city': 'Khulna', 'country': 'Bangladesh'}","[{'project_name': 'ETL Pipeline', 'hours': 150}]",3.0
2,103,Karim,AI,90000,30,2021-06-01,"[Python, TensorFlow, PyTorch]","{'city': 'Rajshahi', 'country': 'Bangladesh'}","[{'project_name': 'Image Classification', 'hou...",2.0
3,104,Nusrat,BI,62000,27,2024-02-12,"[SQL, Power BI, Excel]","{'city': 'Chattogram', 'country': 'Bangladesh'}","[{'project_name': 'Executive Dashboard', 'hour...",5.0
4,105,Tanvir,AI,95000,32,2020-09-20,"[Python, LLM, Pandas]","{'city': 'Dhaka', 'country': 'Bangladesh'}","[{'project_name': 'Recommendation Engine', 'ho...",1.0

In [42]:
# Calculate total salary

df["salary"].sum()

np.int64(382000)

In [43]:
# Calculate average salary
df["salary"].mean()

np.float64(76400.0)

In [44]:
# Find maximum salary

df["salary"].max()

95000

In [45]:
# Find minimum salary

df["salary"].min()

62000

In [46]:
# Count employees

df["employee_id"].count()

np.int64(5)

In [47]:
# Calculate average salary by department

df.groupby("department")["salary"].mean()

department
AI                  92500.0
BI                  62000.0
Data Engineering    67500.0
Name: salary, dtype: float64

In [48]:
# Calculate total salary by department

df.groupby("department")["salary"].sum()

department
AI                  185000
BI                   62000
Data Engineering    135000
Name: salary, dtype: int64

In [49]:
# Count employees by department

df.groupby("department")["employee_id"].count()

department
AI                  2
BI                  1
Data Engineering    2
Name: employee_id, dtype: int64

In [50]:
# Calculate average salary and average age

df.groupby("department")[
    ["salary", "age"]
].mean()

                   salary   age
department
AI                92500.0  31.0
BI                62000.0  27.0
Data Engineering  67500.0  27.0

In [51]:
# Calculate multiple statistics

df.groupby("department").agg(
    {
        "salary": ["min", "max", "mean"],
        "age": ["min", "max", "mean"]
    }
)

                 salary                 age
                    min    max     mean min max  mean
department
AI                90000  95000  92500.0  30  32  31.0
BI                62000  62000  62000.0  27  27  27.0
Data Engineering  65000  70000  67500.0  25  29  27.0